# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broker_message.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "BrokerMessage" do
    optional :uuid, :string, 1
    optional :origin, :string, 2
    optional :message_class, :string, 3
    optional :payload, :message, 4, "google.protobuf.Any"
  end
end

BrokerMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("BrokerMessage").msgclass
