# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generate_pdf.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "GeneratePDF" do
    repeated :pdf_ids, :string, 1
  end
end

GeneratePDF = Google::Protobuf::DescriptorPool.generated_pool.lookup("GeneratePDF").msgclass
